import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

import { Html5Qrcode } from "html5-qrcode";

import {
    checkInVisitor,
    checkOutVisitor,
    getVisitorsInside
} from "../../services/checkLogService";

import { getPassByNumber } from "../../services/passService";

import { toast } from "react-toastify";

import DashboardLayout from "../../components/layout/DashboardLayout";
import LoadingSpinner from "../../components/ui/LoadingSpinner";


const ScanPass = () => {

    const scannerRef = useRef(null);

    const [passNumber, setPassNumber] = useState("");

    const [pass, setPass] = useState(null);

    const [loading, setLoading] = useState(false);

    const [inside, setInside] = useState(false);

    const [scannerRunning, setScannerRunning] =
        useState(false);



    // Start QR scanner


    const startScanner = async () => {

        try {

            const scanner = new Html5Qrcode(
                "qr-reader"
            );

            scannerRef.current = scanner;


            await scanner.start(

                {
                    facingMode: "environment",
                },

                {
                    fps: 10,
                    qrbox: {
                        width: 250,
                        height: 250,
                    },
                },

                async (decodedText) => {

                    console.log(
                        "QR scanned:",
                        decodedText
                    );


                    let scannedPassNumber =
                        decodedText;


                    // QR generated by backend
                    // may contain JSON

                    try {

                        const parsed =
                            JSON.parse(decodedText);


                        if (parsed.passNumber) {

                            scannedPassNumber =
                                parsed.passNumber;

                        }

                    } catch (error) {

                        // QR is plain text

                    }


                    setPassNumber(
                        scannedPassNumber
                    );


                    await stopScanner();

                    await verifyPass(
                        scannedPassNumber
                    );

                },

                (errorMessage) => {

                    // Ignore continuous scanner errors

                }

            );


            setScannerRunning(true);

        } catch (error) {

            console.error(error);

            toast.error(
                "Unable to start camera"
            );

        }

    };



    // Stop scanner


    const stopScanner = async () => {

        if (!scannerRef.current) {
            return;
        }


        try {

            await scannerRef.current.stop();

            scannerRef.current.clear();

        } catch (error) {

            console.error(
                "Scanner stop error:",
                error
            );

        }


        scannerRef.current = null;

        setScannerRunning(false);

    };



    // Cleanup


    useEffect(() => {

        return () => {

            stopScanner();

        };

    }, []);



    // Verify pass


    const verifyPass = async (number) => {

        if (!number) {
            toast.error("Pass number is required");
            return;
        }

        try {

            setLoading(true);
            setPass(null);
            setInside(false);

            const response =
                await getPassByNumber(number);

            setPass(response.data);

            // Check whether visitor is currently inside
            const insideResponse =
                await getVisitorsInside();

            const currentInside =
                (insideResponse.data || []).some(
                    (log) =>
                        log.pass?._id ===
                        response.data._id
                );

            setInside(currentInside);

            toast.success(
                "Pass verified successfully"
            );

        } catch (error) {

            console.error(error);

            toast.error(
                error.response?.data?.message ||
                "Invalid pass"
            );

        } finally {

            setLoading(false);

        }
    };



    // Manual verification


    const handleVerify = async (event) => {

        event.preventDefault();

        await verifyPass(
            passNumber.trim()
        );

    };



    // Check in


    const handleCheckIn = async () => {

        try {

            setLoading(true);


            const response =
                await checkInVisitor(
                    passNumber
                );


            toast.success(
                response.message ||
                "Visitor checked in successfully"
            );


            await verifyPass(
                passNumber
            );

        } catch (error) {

            console.error(error);

            toast.error(
                error.response?.data?.message ||
                "Check-in failed"
            );

        } finally {

            setLoading(false);

        }

    };



    // Check out


    const handleCheckOut = async () => {

        try {

            setLoading(true);


            const response =
                await checkOutVisitor(
                    passNumber
                );


            toast.success(
                response.message ||
                "Visitor checked out successfully"
            );


            await verifyPass(
                passNumber
            );

        } catch (error) {

            console.error(error);

            toast.error(
                error.response?.data?.message ||
                "Check-out failed"
            );

        } finally {

            setLoading(false);

        }

    };


    return (

        <DashboardLayout>
            {loading ? (
                <LoadingSpinner>

                </LoadingSpinner>
            ) : (
                <div className="min-h-screen bg-gray-100">

                    <div className="max-w-5xl mx-auto px-6 py-8">


                        {/* Header */}

                        <div className="flex items-center justify-between mb-8">

                            <div>

                                <h1 className="text-3xl font-bold">
                                    Verify Visitor Pass
                                </h1>

                                <p className="text-gray-500 mt-1">
                                    Scan the visitor QR code or enter the pass number manually.
                                </p>

                            </div>


                            <Link
                                to="/security"
                                className="text-blue-600 hover:underline"
                            >
                                Dashboard
                            </Link>

                        </div>


                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">


                            {/* Scanner */}

                            <div className="bg-white rounded-xl shadow p-6">

                                <h2 className="text-xl font-semibold mb-4">
                                    Scan QR Code
                                </h2>


                                <div
                                    id="qr-reader"
                                    className="w-full"
                                />


                                <div className="flex gap-3 mt-5">

                                    {!scannerRunning ? (

                                        <button
                                            onClick={startScanner}
                                            className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-3 rounded-lg"
                                        >
                                            Start Scanner
                                        </button>

                                    ) : (

                                        <button
                                            onClick={stopScanner}
                                            className="bg-red-600 hover:bg-red-700 text-white px-5 py-3 rounded-lg"
                                        >
                                            Stop Scanner
                                        </button>

                                    )}

                                </div>

                            </div>


                            {/* Manual verification */}

                            <div className="bg-white rounded-xl shadow p-6">

                                <h2 className="text-xl font-semibold mb-4">
                                    Enter Pass Number
                                </h2>


                                <form
                                    onSubmit={handleVerify}
                                    className="space-y-4"
                                >

                                    <input
                                        type="text"
                                        value={passNumber}
                                        onChange={(e) =>
                                            setPassNumber(
                                                e.target.value
                                            )
                                        }
                                        placeholder="VP-2026-ABC123"
                                        className="w-full border rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                                    />


                                    <button
                                        type="submit"
                                        disabled={loading}
                                        className="w-full bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-lg"
                                    >

                                        {loading
                                            ? "Verifying..."
                                            : "Verify Pass"}

                                    </button>

                                </form>

                            </div>

                        </div>


                        {/* Pass result */}

                        {pass && (

                            <div className="bg-white rounded-xl shadow p-6 mt-8">

                                <div className="flex justify-between items-start">

                                    <div>

                                        <h2 className="text-2xl font-bold">
                                            {pass.appointment?.visitor?.fullName}
                                        </h2>

                                        <p className="text-gray-500">
                                            {pass.passNumber}
                                        </p>

                                    </div>


                                    <span
                                        className={`px-4 py-2 rounded-full text-sm font-medium ${pass.status === "Active"
                                            ? "bg-green-100 text-green-700"
                                            : pass.status === "Used"
                                                ? "bg-gray-100 text-gray-700"
                                                : "bg-red-100 text-red-700"
                                            }`}
                                    >

                                        {pass.status}

                                    </span>

                                </div>


                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Visitor
                                        </p>

                                        <p className="font-medium">
                                            {pass.appointment?.visitor?.fullName || "-"}
                                        </p>

                                    </div>


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Phone
                                        </p>

                                        <p className="font-medium">
                                            {pass.appointment?.visitor?.phone || "-"}
                                        </p>

                                    </div>


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Company
                                        </p>

                                        <p className="font-medium">
                                            {pass.appointment?.visitor?.company || "-"}
                                        </p>

                                    </div>


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Host
                                        </p>

                                        <p className="font-medium">
                                            {pass.appointment?.hostName || "-"}
                                        </p>

                                    </div>


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Department
                                        </p>

                                        <p className="font-medium">
                                            {pass.appointment?.department || "-"}
                                        </p>

                                    </div>


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Visit Date
                                        </p>

                                        <p className="font-medium">
                                            {pass.appointment?.visitDate || "-"}
                                        </p>

                                    </div>


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Visit Time
                                        </p>

                                        <p className="font-medium">
                                            {pass.appointment?.visitTime || "-"}
                                        </p>

                                    </div>


                                    <div>

                                        <p className="text-gray-500 text-sm">
                                            Valid Until
                                        </p>

                                        <p className="font-medium">
                                            {pass.validUntil
                                                ? new Date(
                                                    pass.validUntil
                                                ).toLocaleString()
                                                : "-"
                                            }
                                        </p>

                                    </div>

                                </div>


                                {/* Actions */}

                                <div className="flex gap-4 mt-8">


                                    {pass.status === "Active" && !inside && (

                                        <button
                                            onClick={handleCheckIn}
                                            disabled={loading}
                                            className="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg"
                                        >
                                            Check In
                                        </button>

                                    )}


                                    {pass.status === "Active" && inside && (

                                        <button
                                            onClick={handleCheckOut}
                                            disabled={loading}
                                            className="bg-red-600 hover:bg-red-700 text-white px-6 py-3 rounded-lg"
                                        >
                                            Check Out
                                        </button>

                                    )}

                                </div>

                            </div>

                        )}

                    </div>

                </div>
            )}



        </DashboardLayout>

    );

};


export default ScanPass;